# general
seed: 2022
workers: 4

# dataset
data_dir: "./datasets"
data_name: "AgNews"
class_num: 4

# train options
batch_size: 128
start_epoch: 0
epochs: 100


# model options
pretrained_model: "PairSupCon"  # PairSupCon / BERT / SBERT
bert: "pairsupcon-base"  # bertbase / bertlarge / pairsupcon-base / pairsupcon-large ...
feature_dim: 128
max_len: 200  # max len of seq 

check_point_path: "./save/"  # 
reload: False  # continue training or not
use_noise: False
noise_lambda: 0.15 

# loss options
learning_rate: 0.0003
weight_decay: 0.
instance_temperature: 0.5
cluster_temperature: 1.0
